### ISSUE TITLE
Refactor the blast code

### ISSUE THREAD

**Issue by arvestad** [msarrias/exonize#12]
I think clarity would be improved if Blast-related code was refactored into a separate file and class. The Exonize object is quite heavy with many attributes and methods. If blast code was moved to a separate class, it could be instantiated in exonize.py and all its gory details would be "hidden" there, before being shared as an attribute to Exonize. Ideally, the blast abstraction would be so good that Exonize does not even need to know how sequences are compared, but that is not a priority.

**Comment by msarrias** [comment]
@arvestad: you are absolutely right! Thanks for the comment :) 
I aim to take care of this when I come back from Japan.
