### ISSUE TITLE
BiopythonWarning: You may be importing Biopython from inside the source tree

### ISSUE THREAD

**Issue by msarrias** [msarrias/exonize#9]
After installing exonize following the instructions in the readme file I got the following warning:

Did you encounter the same issue?

> /opt/homebrew/lib/python3.11/site-packages/Bio/__init__.py:138: BiopythonWarning: You may be importing Biopython from inside the source tree. This is bad practice and might lead to downstream issues. In particular, you might encounter ImportErrors due to missing compiled C extensions. We recommend that you try running your code from outside the source tree. If you are outside the source tree then you have a setup.py file in an unexpected directory: /opt/homebrew/lib/python3.11/site-packages
  warnings.warn(

**Comment by arvestad** [comment]
I actually do not recognise this. And I have installed exonize several times now. 

I am however installing Biopython in a separate conda environment, and avoid homebrew for any Python packages. It is only recently that Biopython became possible to install using pip/conda though. I have a conda environment for every project, named the same as the GitHub project, and it saves me a lot of headache. 

My Biopython install is 1.81, if that helps, and Python 3.9.18.

**Comment by msarrias** [comment]
I think it relates to this other [issue](https://github.com/biopython/biopython/issues/2318)
